#!/bin/bash

echo "Recompiling $1 if neccesary..."

# make file uses sml to compile
make "TARGET={$1}"

# concat assembly into new file
tigf=$1.s
tmp=tigc.temp
arch=mipstig.s
mv $tigf $tmp
cp $arch $tigf
cat $tmp >> $tigf
rm $tmp

echo "Done!"

echo "Executing $1:"
# execute with spim


